name: 🐞 Feature request
description: Suggest an idea for this project
title: "[FEAT] <title>"
labels: [feature-request]
body:
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe
    description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here
  validations:
    required: false
- type: dropdown
  attributes:
    label: Contributing
    multiple: false
    options:
      - "Yes, I am willing to help implement this feature in a PR"
      - "No, I am afraid I cannot help regarding this"
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      It takes a lot of work and time maintaining this project; any contribution is welcomed
